### ISSUE TITLE
Error on Plugins QConsolidate3

### ISSUE THREAD

**Issue by Martina1895** [danzig666/qconsolidate3#6]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
QGis 3.2

Description error
ModuleNotFoundError: No module named 'osgeo' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/__init__.py", line 25, in classFactory
    from .qconsolidate import QConsolidatePlugin
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/qconsolidate.py", line 34, in 
    from . import qconsolidatedialog
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/qconsolidatedialog.py", line 51, in 
    from .consolidatethread import ConsolidateTask
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 47, in 
    from osgeo import gdal
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osgeo'

Versione Python: 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
Versione di QGIS: 3.2.3-Bonn Bonn, exported 

Percorso Python:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/martinamaines/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by hoge6b01** [comment]
Same here.
Applies to every kind of export format.
3.2.3-Bonn


 CRITICAL    Parse error at line 1, column 1:
             error occurred while parsing element
             Traceback (most recent call last):
              File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 71, in run
              self.consolidate()
              File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 96, in consolidate
              doc = self.loadProject()
              File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 174, in loadProject
              raise SyntaxError(msg)
              File "", line None
             SyntaxError: Parse error at line 1, column 1:
             error occurred while parsing element

**Comment by danzig666** [comment]
Same as #4
